# -*- coding: utf-8 -*-
"""python_powerPoint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mp6vwPQBMUu4Hz9yXF330XGHIh68Ajis
"""

# https://www.youtube.com/watch?v=OafUqA1Efeo

from pptx import Presentation

apresentacao = Presentation()


#editar slides

slide_1 = apresentacao.slides.add_slide(apresentacao.slide_layouts[0])
#slide_2 = apresentacao.slides.add_slide(apresentacao.slide_layouts[2])
#slide_3 = apresentacao.slides.add_slide(apresentacao.slide_layouts[3])

titulo = slide_1.shapes.title
sub_titulo = slide_1.placeholders[1]

titulo.text = "1 slide do vini"
sub_titulo.text = "tamo criando ppt com py"





#salvar esses slides
apresentacao.save("slides1.pptx")
apresentacao.save("slides1.pdf")

#criar ppt personalizados

from pptx import Presentation
from pptx.util import Inches, Pt

apresentacao = Presentation()

x = Inches(1)
y = Inches(2)
larg =  Inches(2)
alt = Inches(2)

slide = apresentacao.slides.add_slide(apresentacao.slide_layouts[6])

caixa = slide.shapes.add_textbox(x,y,larg,alt)
caixa.text = "slide de apresentacao"

text_frame = caixa.text_frame

paragrafo = text_frame.add_paragraph()
paragrafo.text = "by vinni"

paragrafo = text_frame.add_paragraph()
paragrafo.text = "engenheiro de computacao - ufsc"
paragrafo.font.bold = True

paragrafo.font.size = Pt(30)




#salvar esses slides
apresentacao.save("slides0.pptx")

#criar ppt com graficos
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE

apresentacao = Presentation()

slide = apresentacao.slides.add_slide(apresentacao.slide_layouts[6])

#criar grafico
avioes = ["F15","SU27","P51"] #categorias eixo x
ano = [1975,1977,1940] #serie de dados eixo y


x = Inches(1)
y = Inches(2)
larg =  Inches(5)
alt = Inches(3)

dados_grafico = CategoryChartData()
dados_grafico.categories = avioes
dados_grafico.add_series("Avioes - first flight ",ano)
slide.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED,x,y,larg,alt,dados_grafico)

#salvar esses slides
apresentacao.save("slides2.pptx")