# -*- coding: utf-8 -*-
"""Visualizador de dados médicos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EcHt1MimpWAM5QO-QXN0_IFVU6A4K8On
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("medical_examination.csv")
df

df_sample = df.sample(n=10, random_state=42)
df_sample.to_csv('sample.csv')

#coluna de overweight (excesso de peso) aos dados.
#Para determinar se uma pessoa tem excesso de peso, primeiro calcule sua IMC dividindo seu peso em quilogramas pelo quadrado de sua altura em metros.
#Se esse valor é > 25, a pessoa está com excesso de peso. Use o valor 0 para NÃO ter excesso de peso e o valor 1 para tê-lo.
df["imc"] = df["weight"] / ((df["height"]/100) **2)
df

df["excesso de peso"] = np.where(df["imc"] > 25, 1, 0)
df

#Normalize os dados, tornando 0 sempre bom e 1 sempre ruim.
#Se o valor de cholesterol ou de gluc for 1, torne o valor 0. Se o valor for maior que 1, torne o valor 1.