# -*- coding: utf-8 -*-
"""nível do mar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IdO_LYRzbQTl8sSW4mDhvg_tjMWPABmF
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress

df = pd.read_csv("epa-sea-level.csv")
df

df_sample = df.sample(n=10, random_state=42)

# salva a amostra em um novo dataframe
df_sample.to_csv('sample.csv')

plt.scatter(df["Year"], df['CSIRO Adjusted Sea Level'])
plt.xlabel("Ano")
plt.ylabel("CSIRO Adjusted Sea Level")
plt.title("Sea Level Rise")
plt.show()

# Calcule a regressão linear
slope, intercept, r_value, p_value, std_err = linregress(df['Year'], df['CSIRO Adjusted Sea Level'])

# Crie a linha de melhor ajuste
fit_line = slope * df['Year'] + intercept

# Plote a linha de melhor ajuste
plt.plot(df['Year'], fit_line, color='red')

# Extrapole para 2050
future_year = 2050
future_level = slope * future_year + intercept

# Adicione um ponto em 2050 na linha de melhor ajuste
plt.plot([future_year], [future_level], 'ro')