# -*- coding: utf-8 -*-
"""retas_parametricas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UK4eOGsrM75_JZ_4zdboycPr9VN9KG39

A forma paramétrica da equação de uma reta é uma forma de representar uma reta utilizando uma variável chamada parâmetro. Essa variável faz a ligação entre as
 equações que representam a mesma reta.
"""

import numpy as np
import matplotlib.pyplot as plt

# 2 dimensoes

def reta(ponto,direcao,parametro): #(x_ponto,y_ponto),(x_direcao,y_direcao)
  t = parametro
  x = ponto[0] + direcao[0]*t
  y = ponto[1] + direcao[1]*t


  return x, y


ponto = (1, 2)
direcao = (3, 4)

# Calcula os pontos da reta para um intervalo de valores do parâmetro
t = np.arange(0, 1, 0.01)
x, y = reta(ponto, direcao, t)


plt.plot(x, y)

# Mostra o gráfico
plt.show()

import numpy as np
import matplotlib.pyplot as plt
#from mpl_toolkits.mplot3d import Axes3D

#3 dimensoes

def reta(ponto,direcao,parametro): #(x_ponto,y_ponto),(x_direcao,y_direcao)
  t = parametro
  x = ponto[0] + direcao[0]*t
  y = ponto[1] + direcao[1]*t
  z = ponto[2] + direcao[2]*t

  return x, y , z

ponto = (1, 2, 3)
direcao = (3, 4, 5)

# Calcula os pontos da reta para um intervalo de valores do parâmetro
t = np.arange(0, 1, 0.01)
x, y, z = reta(ponto, direcao, t)

# Cria o eixo 3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Plota a reta
ax.plot(x, y, z)

# Mostra o gráfico
plt.show()