# -*- coding: utf-8 -*-
"""retas-3d

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LyXCiIL70BOC93Q8jzLp4qedSD7ir7qa
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Gera os pontos da curva
t = np.linspace(0, 2 * np.pi, 1000)
x = np.sin(t)
y = np.cos(t)
z = t

# Cria o eixo 3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Plota a curva
ax.plot(x, y, z)

# Mostra o gráfico
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Define a função parabólica
def f(x, y):
    return x ** 2 + y ** 2

# Gera os pontos da superfície
x = np.linspace(-2, 2, 100)
y = np.linspace(-2, 2, 100)
X, Y = np.meshgrid(x, y)
Z = f(X, Y)

# Cria o eixo 3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Plota a superfície
ax.plot_surface(X, Y, Z) # (X, Y, Z, cmap='gray')

# Mostra o gráfico
plt.show()