# -*- coding: utf-8 -*-
"""codigo_que_troca_espacos_por__

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qmEi0celQ3B9oMH1S-I2AuXEMVXE4A9I
"""

texto = str(input("Digite o valor: "))
texto_pronto = texto.replace(" ", "_")
texto_pronto = texto_pronto.replace("(", "_")
texto_pronto = texto_pronto.replace(")", "_")

#texto_pronto = texto_pronto.capitalize()
print(texto_pronto)