# -*- coding: utf-8 -*-
"""graos-pythonEX

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xoz-MQO7bMQ4KI3cLTH6ja5l-nI3tV-S
"""

def square(number):
  if(number > 64 or number <= 0 ):
    raise ValueError("square must be between 1 and 64")

  total = 2**(number-1)
  return total

def total():
  total = 1
  for i in range(1,64):
    total += (2**i)

  return total

square(16)

total()