# -*- coding: utf-8 -*-
"""reverse_string

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNffCwFtlBqw_uWjESYibJL_-sMJOZoJ
"""

def reverse(word):
  palavra = word
  ao_contrario = ""

  for i in range(len(palavra)-1,-1,-1):
    ao_contrario+=palavra[i]

  return ao_contrario

print(reverse("robot"))