# -*- coding: utf-8 -*-
"""api_chatGPT

Automatically generated by Colaboratory.


"""

API_KEY = "api"

import requests
import json

headers = {"Authorization": f"Bearer {API_KEY}","Content-Type" : "application/json"}
#requisicao = requests.post(link, headers=headers)

id_modelo = "gpt-3.5-turbo-0613"

link = "https://api.openai.com/v1/chat/completions"
body_msg = {
    "model" : id_modelo ,
    "messages": [{"role": "user", "content" : "fale sobre santos dumont"}]
}

body_msg = json.dumps(body_msg)


requisicao = requests.post(link, headers=headers,data=body_msg)
#print(requisicao)
#print(requisicao.text)
resposta = requisicao.json()
mensagem_resposta = resposta["choices"][0]["message"]["content"]
print(mensagem_resposta)