# -*- coding: utf-8 -*-
"""bacen_api_fea

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hlXTvhpPlRHc9cLWwOa33tKih3RtQS7A
"""

import pandas as pd

cd = 11
def bcb(codigo):
  link = f"https://api.bcb.gov.br/dados/serie/bcdata.sgs.{codigo}/dados?formato=json"
  df = pd.read_json(link)
  df.index = pd.to_datetime(df["data"])
  df = df["valor"]
  return df

selic = bcb(11)
#selic.to_excel("C:\Users\Cliente\Desktop")
selic