# -*- coding: utf-8 -*-
"""fea pandas 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-cTJKKUiZSHoU_YFaa6XkRen7QppJ-bQ
"""

pip install pandas

import pandas as pd

"""series - semelhantes aos arrays do numpy"""

retornos = pd.Series([0.3,0.021, 0.001,-0.05, 0.031],
index = ["Seg","Ter","Qua", "Qui","Sex"])

retornos

retornos["Ter"]

"""https://pandas.pydata.org/docs/reference/api/pandas.Series.html

"""

print("Media ", retornos.mean())
print("Desvio padrao ", retornos.std())

retornos.describe()

"""dataframes - estrutura bidimensional de dados, lembrando uma panilha

```
# Isto está formatado como código
```


"""

df_retornos = pd.DataFrame({"Dia da semana" : ["Seg","Ter","Qua", "Qui","Sex"],
                           "Ativo B" : [0.022,0.10,0.017,-0.07,-0.0051],
                           "Ativo C" : [-0.2,-0.006,0.023,0.009,0.017]})

df_retornos.describe()

df_retornos