# -*- coding: utf-8 -*-
"""fea numpy codigos uteis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzTUI5ISBFUUQ5rMQMCb9QOlu2ftHwAz
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from datetime import datetime

hoje = datetime.now()
hoje

datetime.now().strftime("%d/%m/%Y %H:%M:%S")

date = datetime.now().strftime("%Y-%m-%d")
date

from random import *

randint(1,999)

arr_np = np.array(["UFSC","UNESP","UFRGS"])
np.sort(arr_np)
#type(arr_np)

b = [2.0,5.0,9.0]
h = [0.5,9.0,3.2]

b_array = np.array(b)
h_array = np.array(h)

print(b_array,h_array)

area_tri = np.array((b_array*h_array)/2)
area_tri

a = np.arange(10)

a

np.arange(0,10,2)

np.linspace(0,22,num=5)

k = np.array([1,4,6,4,7,4,5])
c = np.concatenate((k,a))
c_crescente = np.sort(c)
c_crescente

n = 1_000_000_000
print(n)
n_str = str(n)
print(f'Valor = {n:,.2f}')