# -*- coding: utf-8 -*-
"""filmes_py_fea

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZdXPDGVPqhBBVfLEXYElgN3FKTbVYQ6
"""

import numpy as np
import pandas as pd

filmes = pd.read_csv("Filmes.csv", sep=",")
ratings = pd.read_csv("Ratings.csv", sep=";")

filmes.head()

ratings.head()

filmes.shape #tamanho do arquivo e formato de linhas e colunas

ratings.shape

df = filmes.merge(ratings, on="movieId")
df.head()

tabela_filmes = pd.pivot_table(df, index="title",columns="userId",values="rating").fillna(0)

tabela_filmes.head()

import sklearn.metrics.pairwise as pw

rec = pw.cosine_similarity(tabela_filmes)
rec_df = pd.DataFrame(rec,columns=tabela_filmes.index,index=tabela_filmes.index)
rec_df.head()

cossine_df = rec_df['Man of Steel'].sort_values(ascending=False)
cossine_df.columns = ['Recomendaçoes']
cossine_df.head(20)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

dados = pd.read_csv("Dados.csv")
tags = pd.read_csv("Tags.csv")

dados.head()

tags.head()

dados.shape

filmes["movieId"] = filmes["movieId"].apply(lambda x: str(x))

df2 =  filmes.merge(dados, left_on="title", right_on="Name", how="left")
df2 = df2.merge(tags, left_on="movieId",right_on="movieId", how="left")
df2['Infos'] = df2['genres'] + str(df2['Directors_Cast']) + str(df2["Discription"]) + df2["tag"]
df2.head()

vec = TfidfVectorizer()
tfidif = vec.fit_transform(df2['Infos'].apply(lambda x : np.str_(x)))

sim = cosine_similarity(tfidif)
sim

sim_df2 = pd.DataFrame(sim, columns=df2["title"], index=df2["title"])
sim_df2.head()

final_df = pd.DataFrame(sim_df2["Thor"].sort_values(ascending=False))
final_df.columns = ["Recomendaçôes"]
final_df.head(20)