# -*- coding: utf-8 -*-
"""qr_code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mECav0dMHLktDQWodIFEmlmo1rz2Fo9s
"""

pip install python-barcode

pip install pillow

pip install qrcode

"""#Código de barras

"""

from barcode import EAN13
from barcode.writer import ImageWriter
#                                     torna a imagem em png
codigo_barras = EAN13('123123123123', writer=ImageWriter())
codigo_barras.save("codigo_de_barras")

from barcode import EAN13
from barcode.writer import ImageWriter

codigos_produtos = {
    "Feijao": "551746511111",
    "Arroz": "665789011111",
    "Macarrao": "665887111111",
    "Azeite": "998556211111"}

for key in codigos_produtos.keys():
  codigos = EAN13(codigos_produtos[key], writer=ImageWriter())
  codigos.save(key)

"""#QR code"""

import qrcode


imagem = qrcode.make("https://discord.gg/d2kPkskz")
imagem.save("qrcode_disc.png")