# -*- coding: utf-8 -*-
"""carteira_gestao_py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1db5K3sslk7rFotP8vwUh2Kl1cJOPcZ0L
"""

import pandas as pd
import numpy as np
import yfinance as yf

ativos = ["BPAC11.SA","ITUB3.SA","VALE3.SA","EGIE3.SA","WEGE3.SA"]

data_inicio = pd.to_datetime("2019-01-01")
data_fim = pd.to_datetime("2023-12-31")

pesos = np.array([0.2,0.2,0.2,0.2,0.2])

carteira = yf.download(ativos,start=data_inicio,end=data_fim)["Adj Close"]
carteira

retornos = carteira.pct_change()
retornos.dropna(inplace=True)
retornos

#retorno do portifolio = somatorio(peso * retorno de cada)
retorno_carteira = (retornos*pesos).sum(axis=1)
retorno_portifolio = pd.DataFrame()
retorno_portifolio["Retornos"] = retorno_carteira
retorno_portifolio

"""#Correlacao entre os retornos dos ativos

"""

#risco da carteira
import seaborn as sns

corr = retornos.corr()
sns.heatmap(corr,annot=True)

"""#Matriz de covariancia"""

cov = retornos.cov()
cov

"""#Funcao de risco da carteira"""

def volatividade_carteira(precos,pesos,cov):
  volat_diaria = np.sqrt(np.dot(pesos.T,np.dot(cov,pesos)))

  volt_anualizada = volat_diaria*np.sqrt(252)
  return volt_anualizada

volatividade_carteira(carteira,pesos,cov) #

"""#Comparacao com Benchmark"""

def benchmark_ibov(data_inicio,data_fim,df_precos):
  ibov = yf.download("^BVSP",start=data_inicio,end=data_fim)["Close"]
  df_precos = df_precos.pct_change()
  df_precos.fillna(0,inplace=True)
  df_precos = (1+df_precos).cumprod()
  df_precos =pd.Series((df_precos*pesos).sum(axis=1),name="Carteira")

  ibov_retornos = ibov.pct_change()
  ibov_retornos.fillna(0,inplace=True)
  benchmark_ibov = (1+ibov_retornos).cumprod()
  benchmark = pd.merge(df_precos,benchmark_ibov, how="inner", left_index=True,right_index=True)
  benchmark.rename(columns={"Close":"IBOV"},inplace=True)
  return benchmark.iloc[-1], benchmark.plot(figsize=(10,6))

benchmark_ibov(data_inicio,data_fim,carteira)

#carteira multiplicou seu capital por 3.26
#ibov multiplicou seu capital por 1.47
#https://www.youtube.com/watch?v=io67O4VElQE