""""
pyuic5 conversor.ui -o conversor.py
pyuic5 conversor.ui -o conversor.py -x
-x add main
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conversor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from PyQt5 import *


class Ui_conversor(object):
    def setupUi(self, conversor):
        conversor.setObjectName("conversor")
        conversor.resize(562, 235)
        self.centralwidget = QtWidgets.QWidget(conversor)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_converter = QtWidgets.QPushButton(self.centralwidget)
        self.btn_converter.setGeometry(QtCore.QRect(120, 170, 75, 23))
        self.btn_converter.setObjectName("btn_converter")
        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(290, 170, 75, 23))
        self.btn_sair.setObjectName("btn_sair")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 511, 21))
        self.label.setObjectName("label")
        self.entrada_tempF = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_tempF.setGeometry(QtCore.QRect(190, 100, 113, 20))
        self.entrada_tempF.setObjectName("entrada_tempF")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 91, 16))
        self.label_2.setObjectName("label_2")
        conversor.setCentralWidget(self.centralwidget)

        self.retranslateUi(conversor)
        self.btn_sair.clicked.connect(conversor.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(conversor)

        self.btn_converter.clicked.connect(self.converte)


    def converte(self):
        temp = float(self.entrada_tempF.text())
        temp = (temp-32)* 10/18

        msg = QtWidgets.QMessageBox()
        #msg.setIcon(msg.information)
        msg.setWindowTitle("Sucesso")

        msg.setText("Resultado: " + str(temp)+ " °C")
        msg.exec()

    def retranslateUi(self, conversor):
        _translate = QtCore.QCoreApplication.translate
        conversor.setWindowTitle(_translate("conversor", "Conversor de Temperatura"))
        self.btn_converter.setText(_translate("conversor", "Converter"))
        self.btn_sair.setText(_translate("conversor", "Sair"))
        self.label.setText(_translate("conversor", "<html><head/><body><p><span style=\" font-size:14pt; color:#aa0000;\">Informe a temperatura em Fahrenheit(°F) para Celsius(°C)</span></p></body></html>"))
        self.label_2.setText(_translate("conversor", "<html><head/><body><p><span style=\" font-size:10pt; color:#005500;\">Temperatura:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    conversor = QtWidgets.QMainWindow()
    ui = Ui_conversor()
    ui.setupUi(conversor)
    conversor.show()
    sys.exit(app.exec_())





