# -*- coding: utf-8 -*-
"""gemini api

Automatically generated by Colaboratory.

Original file is located at
    
"""

pip install -q -U google-generativeai

import pathlib
import textwrap

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

# Used to securely store your API key
from google.colab import userdata


genai.configure(api_key="###")

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

model = genai.GenerativeModel('gemini-pro')

# Commented out IPython magic to ensure Python compatibility.
# %%time
# response = model.generate_content("o que foi a apollo 11")

to_markdown(response.text)

resposta = model.generate_content("fale sobre o caça f15")
to_markdown(resposta.text)

"""# Chat conversations"""

model = genai.GenerativeModel('gemini-pro')
chat = model.start_chat(history=[])
chat

response = chat.send_message("fale sobre santos dumont")
to_markdown(response.text)

chat.history

response = chat.send_message("qual foi o nome do primeiro aviao dele")
to_markdown(response.text)