# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpt_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import json

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_api_gpt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_api_gpt.setGeometry(QtCore.QRect(30, 30, 75, 23))
        self.btn_api_gpt.setObjectName("btn_api_gpt")
        self.api_gpt = QtWidgets.QLineEdit(self.centralwidget)
        self.api_gpt.setGeometry(QtCore.QRect(130, 30, 251, 21))
        self.api_gpt.setObjectName("api_gpt")
        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(30, 530, 121, 21))
        self.btn_sair.setObjectName("btn_sair")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 80, 258, 242))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.texto_prompt = QtWidgets.QTextEdit(self.widget)
        self.texto_prompt.setObjectName("texto_prompt")
        self.verticalLayout.addWidget(self.texto_prompt)
        self.btn_enviar_prompt = QtWidgets.QPushButton(self.widget)
        self.btn_enviar_prompt.setObjectName("btn_enviar_prompt")
        self.verticalLayout.addWidget(self.btn_enviar_prompt)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(330, 80, 441, 471))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gpt_texto = QtWidgets.QTextBrowser(self.widget1)
        self.gpt_texto.setObjectName("gpt_texto")
        self.verticalLayout_2.addWidget(self.gpt_texto)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btn_sair.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn_api_gpt.clicked.connect(self.get_api)

        self.btn_enviar_prompt.clicked.connect(self.get_and_send_prompt)

    def get_api(self):
        api_key = str(self.api_gpt.text())
        return api_key
    

    def get_and_send_prompt(self):
        prompt = str(self.texto_prompt.toPlainText())

        headers = {"Authorization": f"Bearer {self.get_api()}","Content-Type" : "application/json"}

        id_modelo = "gpt-3.5-turbo-0613"

        link = "https://api.openai.com/v1/chat/completions"
        body_msg = {
        "model" : id_modelo ,
        "messages": [{"role": "user", "content" : f"{prompt}"}]
        }

        body_msg = json.dumps(body_msg)

        requisicao = requests.post(link, headers=headers,data=body_msg)
        resposta = requisicao.json()
        mensagem_resposta = resposta["choices"][0]["message"]["content"]

        self.gpt_texto.setText(mensagem_resposta)






        



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_api_gpt.setText(_translate("MainWindow", "Ativar API"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))
        self.label.setText(_translate("MainWindow", "Digite aqui: "))
        self.btn_enviar_prompt.setText(_translate("MainWindow", "Enviar Prompt"))
        self.label_2.setText(_translate("MainWindow", "GPT:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
