# -*- coding: utf-8 -*-
"""arquivos_py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jvN_AyORCu-ECj82QEX6bYIyHR-rcAnu
"""

#with open(nome_arquivo, objetivo em abrir o arquivo)
#read -> para arquivos simples(senhas,tokens, informacoes unicas)
#readlines -> para arquivos maiores

with open("email.txt","r") as arquivo:
 email = arquivo.read()

print(email)

with open("mensagem.txt","r",encoding="utf-8") as mensagem:
  msg = mensagem.readlines()

print(msg)

for linha in msg:
  if "faturamento" in linha:
    print(linha)

#w - write

with open("nova_senha.txt","w") as arquivo:
 arquivo.write("vini-dias")

#append - a -adicionar
with open("email.txt","a") as arquivo:
 arquivo.write("\nvini@email.com")