# -*- coding: utf-8 -*-
"""api via cep

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HZdT9PiVt07m9nSzIjYy_MXhiOSqzzbH
"""

import requests

"""**Consulta das informaçoes de um cep**"""

cep = "88900037"
link = f"https://viacep.com.br/ws/{cep}/json/"

requisicao = requests.get(link)
print(requisicao)
print(requisicao.json())

dicionario = requisicao.json()

cidade = dicionario["localidade"]

print(cidade)

"""**Pesquisa de cep a partir de endereço**"""

estado = "SC"
cidade= "Araranguá"
endereco = "Avenida Getúlio Vargas"
link = f"https://viacep.com.br/ws/{estado}/{cidade}/{endereco}/json/"

requisicao = requests.get(link)
print(requisicao)

dicionario = requisicao.json()
print(dicionario)
"""for elemento in dicionario:
  print(elemento)
  print("\n")"""

import pandas as pd
tabela = pd.DataFrame(dicionario)
display(tabela)

import pprint as  p
p.pprint(dicionario)