# -*- coding: utf-8 -*-
"""bdr_gestao_py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w0KZZ0vIhD9sVa9MryDW2JL5VYbIz_rf
"""

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

#Uma análise e geração de relatório com Python
#https://www.youtube.com/watch?v=CvhZaDpBQsg&list=PLP_dh3S9H39kNe5wZ3PTMYqkGZHkn8FGQ&index=3

data_inicio = pd.to_datetime("2019-01-01")
data_fim = pd.to_datetime("2023-12-31")

#captura dos dados
carteira = yf.download(["BPAC11.SA","ITUB3.SA","VALE3.SA","EGIE3.SA","WEGE3.SA"],start=data_inicio,end=data_fim)["Adj Close"]

#carteira.head()
carteira.plot()

apple = carteira.ffill(axis = 0)

apple.plot()

apple_normalizado = apple/apple.iloc[0]
#1 real inicial investido teria se transformado em X
apple_normalizado

(apple/apple.iloc[0]).plot()

"""#Criando rotina para várias janelas de tempo"""

datas_inicio = ["2019-01-01","2021-01-01","2023-01-01"]

def compara_ativos(inicio):
  carteira = yf.download(["BPAC11.SA","ITUB3.SA","VALE3.SA","EGIE3.SA","WEGE3.SA"],start=inicio)["Adj Close"]
  carteira = carteira.ffill(axis = 0)
  #carteira = carteira.dropna()
  carteira = carteira/carteira.iloc[0]
  carteira.plot(figsize=(10, 6))

datas_inicio = ["2019-01-01","2021-01-01","2023-01-01"]

compara_ativos(data_inicio[1])

#criando loop para geração do relatorio
relatorio = PdfPages("relatorio_minhas_acoes.pdf")

for data in datas_inicio:
  relatorio.savefig(compara_ativos(data))

relatorio.close()

#mensurar impacto do cambio
data_inicio = pd.to_datetime("2019-01-01")
data_fim = pd.to_datetime("2023-12-31")

#captura dos dados
dados = yf.download(["AAPL","AAPL34.SA","USDBRL=X"],start=data_inicio,end=data_fim)["Adj Close"]
dados = dados.ffill(axis = 0)

dados.head()

dados["apple_reais"] = dados["AAPL"] * dados["USDBRL=X"]
dados = dados.dropna()
dados.head()

#normalizar todo o dataframe
dados_normalizado = dados/dados.iloc[0]
dados_normalizado

dados_normalizado.plot()