# -*- coding: utf-8 -*-
"""mat_plot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vD3ZCZNNRYwWusHQPJeYT49m0HeiuY8K
"""

import matplotlib.pyplot as plt

x = [1,2,3,4]
y = [2,3,4,3]

plt.plot(x,y,label="Dados")
plt.ylabel("Eixo y")
plt.xlabel("Eixo x")
plt.title("Titulo-")
plt.xticks([0,2,4,6,8])
plt.yticks([0,2,4,6,8])
plt.legend()

plt.show()

plt.plot(x,y,linestyle="-")
plt.axis(xmin=0,xmax=5,ymin=0,ymax=5)
plt.show()

"""plot()
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html?highlight=pyplot%20plot#matplotlib-pyplot-plot

LINES propriedades
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_marker

.Scatter()
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html#matplotlib-pyplot-scatter

.Scatter()
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html#matplotlib-pyplot-scatter

Mudando os tipos de marcadores do gráfico :
https://matplotlib.org/stable/api/markers_api.html#module-matplotlib.markers

Mudando os tipos de marcadores do gráfico :
https://matplotlib.org/stable/api/markers_api.html#module-matplotlib.markers


FIGURE
https://matplotlib.org/stable/api/figure_api.html?highlight=sharex#module-matplotlib.figure

SUBPLOTS
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot.html

Aplicação: Fonte de dados Kaggle
https://www.kaggle.com/mattiuzc/stock-exchange-data


"""

figura = plt.figure(figsize=(25,3))
figura.suptitle("Titulo figura")
#plt.axis(xmin=0,ymin=0,)
figura.add_subplot(131)# 1 linha 3 colunas grafico 1
plt.plot(x,y)

plt.show(figura)