# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q8WvhW0yJy41ZlQ4UnaO6rpvBCc7It72

# Gráficos no Python - Matplotlib.pyplot

Para ter acesso a documentação desta biblioteca: https://matplotlib.org/stable/tutorials/introductory/pyplot.html

## Instalação

No caso do Anaconda (Jupyter) o Matplolib já está instalado.

Não sabe se está instalado ou não? Use o comando pip freeze no prompt de comando

Use pip install -U matplotlib no prompt do Anaconda para atualizar para a versão mais recente

## Importação
"""

import matplotlib.pyplot as plt

"""### plot()
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html?highlight=pyplot%20plot#matplotlib-pyplot-plot
"""

x =[1,2,3,4]
y = [2,3,4,3]

plt.plot(x, y)
plt.show()

"""![image.png](attachment:image.png)"""

x =[1,2,3,4]
y = [2,3,4,3]
plt.plot( x, y, label='dados' )
plt.ylabel('Eixo y')
plt.xlabel('Eixo x')
plt.title('Título do Gráfico')
plt.xticks([0,2,4,6,8,9])
plt.yticks([-1,3,5,9,11])
plt.legend()
plt.show()

"""## LINES propriedades
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_marker
"""

plt.plot (x,y,ls=':', color='#611710', lw=10.0)
plt.show()

"""## .Scatter()

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html#matplotlib-pyplot-scatter
"""

plt.scatter(x,y, color = 'k')
plt.show()

"""## .bar()

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.bar.html#matplotlib-pyplot-bar
"""

plt.bar(x,y, color = 'r')
plt.show()

"""### Nomeando os eixos de um gráfico:

### Mudando os tipos de marcadores do gráfico :
https://matplotlib.org/stable/api/markers_api.html#module-matplotlib.markers
"""

plt.scatter(x,y, color = 'k', marker = 'v')
plt.show()

"""### Alterando os limites dos gráficos:
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axis.html#matplotlib.pyplot.axis
"""

plt.plot(x,y)
plt.axis('square')
plt.show()

"""### FIGURE
https://matplotlib.org/stable/api/figure_api.html?highlight=sharex#module-matplotlib.figure

### SUBPLOTS
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot.html

"""



valoresx = [1, 2, 3, 4]
valoresy = [1, 4, 2, 3]


figura = plt.figure(figsize=(20,3))
figura.suptitle('Título Geral')


figura.add_subplot(131)
plt.plot(valoresx, valoresy, label='Um dado qualquer')
plt.legend()
plt.title('Gráfico 1')

figura.add_subplot(132)
plt.scatter(valoresx,valoresy)
plt.title('Gráfico 2')

figura.add_subplot(133)
plt.bar(valoresx, valoresy)
plt.title('Gráfico 3')

plt.savefig('gráficos.png')

plt.show(figura)

"""## Aplicação: Fonte de dados Kaggle

https://www.kaggle.com/mattiuzc/stock-exchange-data
"""

import pandas as pd

cotacao_df = pd.read_csv('indexdata.csv')
display(cotacao_df)

cotacao_df1 = cotacao_df[['Index','Date','Close']]
display(cotacao_df1)

dfremove = cotacao_df1.loc[(cotacao_df1['Index']!='NYA')]
cotacao_dffinal = cotacao_df1.drop(dfremove.index)
display(cotacao_dffinal)
cotacao_dffinal = cotacao_dffinal[13900:]
display(cotacao_dffinal)

plt.figure(figsize=(20,4))
plt.plot(cotacao_dffinal['Date'], cotacao_dffinal['Close'], label ='NYA', color = 'g', ls='--', lw="2")
plt.legend( loc= 2, fontsize= 18)
plt.ylabel('Valor do Fechamento')
plt.xlabel('Data da Cotação')
plt.title('Gráfico de cotação histórica da Bolsa NYA')
plt.xticks(['2021-03-23','2021-04-23', '2021-05-03'])

plt.show()







